# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 460)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 110, 61, 301))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 110, 61, 301))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 110, 61, 301))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 110, 61, 301))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 110, 61, 301))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(310, 110, 61, 301))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(370, 110, 61, 301))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(50, 110, 41, 181))
        self.pushButton_15.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(610, 110, 61, 301))
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(550, 110, 61, 301))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(730, 110, 61, 301))
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(670, 110, 61, 301))
        self.pushButton_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(490, 110, 61, 301))
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(790, 110, 61, 301))
        self.pushButton_13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(430, 110, 61, 301))
        self.pushButton_14.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(110, 110, 41, 181))
        self.pushButton_16.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(230, 110, 41, 181))
        self.pushButton_18.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(290, 110, 41, 181))
        self.pushButton_19.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(350, 110, 41, 181))
        self.pushButton_17.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(470, 110, 41, 181))
        self.pushButton_20.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(530, 110, 41, 181))
        self.pushButton_21.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(650, 110, 41, 181))
        self.pushButton_22.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(710, 110, 41, 181))
        self.pushButton_23.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(770, 110, 41, 181))
        self.pushButton_24.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(770, 10, 81, 91))
        self.pushButton_25.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"selection-background-color: rgb(205, 205, 255);")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(680, 10, 81, 91))
        self.pushButton_26.setStyleSheet("background-color: rgb(255, 184, 166);\n"
"selection-background-color: rgb(255, 215, 205);")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(10, 10, 111, 91))
        self.pushButton_27.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"selection-background-color: rgb(155, 255, 203);")
        self.pushButton_27.setObjectName("pushButton_27")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MIDI"))
        self.pushButton.setText(_translate("MainWindow", "C"))
        self.pushButton_2.setText(_translate("MainWindow", "D"))
        self.pushButton_3.setText(_translate("MainWindow", "E"))
        self.pushButton_4.setText(_translate("MainWindow", "F"))
        self.pushButton_5.setText(_translate("MainWindow", "G"))
        self.pushButton_6.setText(_translate("MainWindow", "A"))
        self.pushButton_7.setText(_translate("MainWindow", "H"))
        self.pushButton_15.setText(_translate("MainWindow", "С1"))
        self.pushButton_8.setText(_translate("MainWindow", "F"))
        self.pushButton_9.setText(_translate("MainWindow", "E"))
        self.pushButton_10.setText(_translate("MainWindow", "A"))
        self.pushButton_11.setText(_translate("MainWindow", "G"))
        self.pushButton_12.setText(_translate("MainWindow", "D"))
        self.pushButton_13.setText(_translate("MainWindow", "H"))
        self.pushButton_14.setText(_translate("MainWindow", "C"))
        self.pushButton_16.setText(_translate("MainWindow", "D1"))
        self.pushButton_18.setText(_translate("MainWindow", "F1"))
        self.pushButton_19.setText(_translate("MainWindow", "G1"))
        self.pushButton_17.setText(_translate("MainWindow", "A1"))
        self.pushButton_20.setText(_translate("MainWindow", "С1"))
        self.pushButton_21.setText(_translate("MainWindow", "D1"))
        self.pushButton_22.setText(_translate("MainWindow", "F1"))
        self.pushButton_23.setText(_translate("MainWindow", "G1"))
        self.pushButton_24.setText(_translate("MainWindow", "A1"))
        self.pushButton_25.setText(_translate("MainWindow", "Convert"))
        self.pushButton_26.setText(_translate("MainWindow", "Record"))
        self.pushButton_27.setText(_translate("MainWindow", "Change sound"))
