# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 460)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cl_button = QtWidgets.QPushButton(self.centralwidget)
        self.cl_button.setGeometry(QtCore.QRect(10, 110, 61, 301))
        self.cl_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.cl_button.setObjectName("cl_button")
        self.dl_button = QtWidgets.QPushButton(self.centralwidget)
        self.dl_button.setGeometry(QtCore.QRect(70, 110, 61, 301))
        self.dl_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.dl_button.setObjectName("dl_button")
        self.el_button = QtWidgets.QPushButton(self.centralwidget)
        self.el_button.setGeometry(QtCore.QRect(130, 110, 61, 301))
        self.el_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.el_button.setObjectName("el_button")
        self.fl_button = QtWidgets.QPushButton(self.centralwidget)
        self.fl_button.setGeometry(QtCore.QRect(190, 110, 61, 301))
        self.fl_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.fl_button.setObjectName("fl_button")
        self.gl_button = QtWidgets.QPushButton(self.centralwidget)
        self.gl_button.setGeometry(QtCore.QRect(250, 110, 61, 301))
        self.gl_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.gl_button.setObjectName("gl_button")
        self.al_button = QtWidgets.QPushButton(self.centralwidget)
        self.al_button.setGeometry(QtCore.QRect(310, 110, 61, 301))
        self.al_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.al_button.setObjectName("al_button")
        self.hl_button = QtWidgets.QPushButton(self.centralwidget)
        self.hl_button.setGeometry(QtCore.QRect(370, 110, 61, 301))
        self.hl_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.hl_button.setObjectName("hl_button")
        self.cl1_button = QtWidgets.QPushButton(self.centralwidget)
        self.cl1_button.setGeometry(QtCore.QRect(50, 110, 41, 181))
        self.cl1_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.cl1_button.setObjectName("cl1_button")
        self.fh_button = QtWidgets.QPushButton(self.centralwidget)
        self.fh_button.setGeometry(QtCore.QRect(610, 110, 61, 301))
        self.fh_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.fh_button.setObjectName("fh_button")
        self.eh_button = QtWidgets.QPushButton(self.centralwidget)
        self.eh_button.setGeometry(QtCore.QRect(550, 110, 61, 301))
        self.eh_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.eh_button.setObjectName("eh_button")
        self.ah_button = QtWidgets.QPushButton(self.centralwidget)
        self.ah_button.setGeometry(QtCore.QRect(730, 110, 61, 301))
        self.ah_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.ah_button.setObjectName("ah_button")
        self.gh_button = QtWidgets.QPushButton(self.centralwidget)
        self.gh_button.setGeometry(QtCore.QRect(670, 110, 61, 301))
        self.gh_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.gh_button.setObjectName("gh_button")
        self.dh_button = QtWidgets.QPushButton(self.centralwidget)
        self.dh_button.setGeometry(QtCore.QRect(490, 110, 61, 301))
        self.dh_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.dh_button.setObjectName("dh_button")
        self.hh_button = QtWidgets.QPushButton(self.centralwidget)
        self.hh_button.setGeometry(QtCore.QRect(790, 110, 61, 301))
        self.hh_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.hh_button.setObjectName("hh_button")
        self.ch_button = QtWidgets.QPushButton(self.centralwidget)
        self.ch_button.setGeometry(QtCore.QRect(430, 110, 61, 301))
        self.ch_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(186, 186, 186);")
        self.ch_button.setObjectName("ch_button")
        self.dl1_button = QtWidgets.QPushButton(self.centralwidget)
        self.dl1_button.setGeometry(QtCore.QRect(110, 110, 41, 181))
        self.dl1_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.dl1_button.setObjectName("dl1_button")
        self.fl1_button = QtWidgets.QPushButton(self.centralwidget)
        self.fl1_button.setGeometry(QtCore.QRect(230, 110, 41, 181))
        self.fl1_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.fl1_button.setObjectName("fl1_button")
        self.gl1_button = QtWidgets.QPushButton(self.centralwidget)
        self.gl1_button.setGeometry(QtCore.QRect(290, 110, 41, 181))
        self.gl1_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.gl1_button.setObjectName("gl1_button")
        self.al1_button = QtWidgets.QPushButton(self.centralwidget)
        self.al1_button.setGeometry(QtCore.QRect(350, 110, 41, 181))
        self.al1_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.al1_button.setObjectName("al1_button")
        self.ch1_button = QtWidgets.QPushButton(self.centralwidget)
        self.ch1_button.setGeometry(QtCore.QRect(470, 110, 41, 181))
        self.ch1_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.ch1_button.setObjectName("ch1_button")
        self.dh1_button = QtWidgets.QPushButton(self.centralwidget)
        self.dh1_button.setGeometry(QtCore.QRect(530, 110, 41, 181))
        self.dh1_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.dh1_button.setObjectName("dh1_button")
        self.fh1_button = QtWidgets.QPushButton(self.centralwidget)
        self.fh1_button.setGeometry(QtCore.QRect(650, 110, 41, 181))
        self.fh1_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.fh1_button.setObjectName("fh1_button")
        self.gh1_button = QtWidgets.QPushButton(self.centralwidget)
        self.gh1_button.setGeometry(QtCore.QRect(710, 110, 41, 181))
        self.gh1_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.gh1_button.setObjectName("gh1_button")
        self.ah1_button = QtWidgets.QPushButton(self.centralwidget)
        self.ah1_button.setGeometry(QtCore.QRect(770, 110, 41, 181))
        self.ah1_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(77, 77, 77);")
        self.ah1_button.setObjectName("ah1_button")
        self.convert_button = QtWidgets.QPushButton(self.centralwidget)
        self.convert_button.setGeometry(QtCore.QRect(770, 10, 81, 91))
        self.convert_button.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"selection-background-color: rgb(205, 205, 255);")
        self.convert_button.setObjectName("convert_button")
        self.record_button = QtWidgets.QPushButton(self.centralwidget)
        self.record_button.setGeometry(QtCore.QRect(680, 10, 81, 91))
        self.record_button.setStyleSheet("background-color: rgb(255, 184, 166);\n"
"selection-background-color: rgb(255, 215, 205);")
        self.record_button.setObjectName("record_button")
        self.change_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_button.setGeometry(QtCore.QRect(10, 10, 111, 91))
        self.change_button.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"selection-background-color: rgb(155, 255, 203);")
        self.change_button.setObjectName("change_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MIDI"))
        self.cl_button.setText(_translate("MainWindow", "C"))
        self.dl_button.setText(_translate("MainWindow", "D"))
        self.el_button.setText(_translate("MainWindow", "E"))
        self.fl_button.setText(_translate("MainWindow", "F"))
        self.gl_button.setText(_translate("MainWindow", "G"))
        self.al_button.setText(_translate("MainWindow", "A"))
        self.hl_button.setText(_translate("MainWindow", "H"))
        self.cl1_button.setText(_translate("MainWindow", "С1"))
        self.fh_button.setText(_translate("MainWindow", "F"))
        self.eh_button.setText(_translate("MainWindow", "E"))
        self.ah_button.setText(_translate("MainWindow", "A"))
        self.gh_button.setText(_translate("MainWindow", "G"))
        self.dh_button.setText(_translate("MainWindow", "D"))
        self.hh_button.setText(_translate("MainWindow", "H"))
        self.ch_button.setText(_translate("MainWindow", "C"))
        self.dl1_button.setText(_translate("MainWindow", "D1"))
        self.fl1_button.setText(_translate("MainWindow", "F1"))
        self.gl1_button.setText(_translate("MainWindow", "G1"))
        self.al1_button.setText(_translate("MainWindow", "A1"))
        self.ch1_button.setText(_translate("MainWindow", "С1"))
        self.dh1_button.setText(_translate("MainWindow", "D1"))
        self.fh1_button.setText(_translate("MainWindow", "F1"))
        self.gh1_button.setText(_translate("MainWindow", "G1"))
        self.ah1_button.setText(_translate("MainWindow", "A1"))
        self.convert_button.setText(_translate("MainWindow", "Convert"))
        self.record_button.setText(_translate("MainWindow", "Record"))
        self.change_button.setText(_translate("MainWindow", "Change sound"))
